name: Build and Release RPM

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-builder

jobs:
  build-rpm:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up variables
      id: vars
      run: |
        # Extract version from tag (remove 'v' prefix)
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        
        # Generate release name
        echo "release_name=krunner-bazaar $VERSION" >> $GITHUB_OUTPUT
        
        # Set container image tag
        echo "image_tag=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$VERSION" >> $GITHUB_OUTPUT
    
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build development container
      run: |
        docker build -t ${{ steps.vars.outputs.image_tag }} -f Containerfile .
        docker push ${{ steps.vars.outputs.image_tag }}
    
    - name: Create RPM build structure
      run: |
        mkdir -p rpmbuild/{SOURCES,SPECS,BUILD,RPMS,SRPMS}
    
    - name: Create source tarball
      run: |
        git archive --format=tar.gz --prefix=krunner-bazaar-${{ steps.vars.outputs.version }}/ HEAD > rpmbuild/SOURCES/krunner-bazaar-${{ steps.vars.outputs.version }}.tar.gz
    
    - name: Copy spec file
      run: |
        cp krunner-bazaar.spec rpmbuild/SPECS/
    
    - name: Build RPM
      run: |
        docker run --rm \
          --volume "$(pwd):/workspace" \
          --workdir /workspace \
          ${{ steps.vars.outputs.image_tag }} \
          bash -c "
            set -euo pipefail
            
            # Build the RPM
            rpmbuild --define '_topdir /workspace/rpmbuild' \
                     --define 'version ${{ steps.vars.outputs.version }}' \
                     -ba rpmbuild/SPECS/krunner-bazaar.spec
          "
    
    - name: List built packages
      run: |
        echo "Built RPM packages:"
        find rpmbuild/RPMS -name "*.rpm" -type f
        find rpmbuild/SRPMS -name "*.rpm" -type f
    
    - name: Prepare release artifacts
      run: |
        mkdir -p release-artifacts
        
        # Copy RPM packages
        find rpmbuild/RPMS -name "*.rpm" -type f -exec cp {} release-artifacts/ \;
        find rpmbuild/SRPMS -name "*.rpm" -type f -exec cp {} release-artifacts/ \;
        
        # Create checksums
        cd release-artifacts
        sha256sum *.rpm > SHA256SUMS
        cd ..
        
        # List artifacts
        echo "Release artifacts:"
        ls -la release-artifacts/
    
    - name: Generate release notes
      id: release_notes
      run: |
        cat > release_notes.md << EOF
        # krunner-bazaar ${{ steps.vars.outputs.version }}
        
        KDE KRunner plugin for searching Flatpak applications via Bazaar.
        
        ## Installation
        
        ### From RPM (Fedora/RHEL/CentOS)
        
        Download the appropriate RPM for your architecture and install:
        
        \`\`\`bash
        # For the main plugin
        sudo dnf install krunner-bazaar-${{ steps.vars.outputs.version }}-1.fc42.x86_64.rpm
        
        # For CLI tools (optional)
        sudo dnf install krunner-bazaar-tools-${{ steps.vars.outputs.version }}-1.fc42.x86_64.rpm
        \`\`\`
        
        ### Requirements
        
        - KDE Frameworks 6
        - Qt 6.5+
        - Flatpak
        - Bazaar (Flatpak application store)
        
        ## Features
        
        - Search for Flatpak applications directly from KRunner
        - Integration with Bazaar's D-Bus SearchProvider interface
        - Shows application metadata including names, descriptions, and icons
        - Filters out already installed applications
        - Includes CLI testing tool for debugging D-Bus interactions
        
        ## Files in this release
        
        - \`krunner-bazaar-${{ steps.vars.outputs.version }}-1.fc42.x86_64.rpm\` - Main KRunner plugin
        - \`krunner-bazaar-tools-${{ steps.vars.outputs.version }}-1.fc42.x86_64.rpm\` - CLI debugging tools
        - \`krunner-bazaar-${{ steps.vars.outputs.version }}-1.fc42.src.rpm\` - Source RPM
        - \`SHA256SUMS\` - Checksums for verification
        
        ## Verification
        
        Verify the integrity of downloaded files:
        
        \`\`\`bash
        sha256sum -c SHA256SUMS
        \`\`\`
        EOF
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.vars.outputs.tag }}
        name: ${{ steps.vars.outputs.release_name }}
        body_path: release_notes.md
        files: |
          release-artifacts/*.rpm
          release-artifacts/SHA256SUMS
        draft: false
        prerelease: false
    
    - name: Update latest tag
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag -f latest
        git push origin latest --force
